"""initial schema

Revision ID: baa89440b9ab
Revises: 
Create Date: 2026-05-17 21:55:19.820337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa89440b9ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('company_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('content_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default="'Borrador'", nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.Column('updated_at', sa.String(), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.Column('finalized_at', sa.String(), nullable=True),
    sa.Column('sent_at', sa.String(), nullable=True),
    sa.CheckConstraint("status IN ('Borrador', 'Finalizado', 'Enviado')", name='ck_documents_status'),
    sa.CheckConstraint("type IN ('quote', 'report')", name='ck_documents_type'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index('idx_documents_client_status', 'documents', ['client_id', 'status', 'updated_at'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_num', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_num', name='uq_document_versions')
    )
    op.create_index('idx_document_versions_doc', 'document_versions', ['document_id', 'version_num'], unique=False)
    op.create_table('quotes',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.String(), nullable=False),
    sa.Column('observations', sa.String(), nullable=True),
    sa.Column('neto', sa.Float(), server_default='0', nullable=False),
    sa.Column('iva', sa.Float(), server_default='0', nullable=False),
    sa.Column('total', sa.Float(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('reports',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('send_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('sent_at', sa.String(), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['quotes.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quote_items_position', 'quote_items', ['document_id', 'position'], unique=False)
    op.create_table('report_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('content_json', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['reports.document_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['report_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_report_sections_parent', 'report_sections', ['document_id', 'parent_id', 'position'], unique=False)
    # ### end Alembic commands ###

    # --- FTS5 virtual table ---
    op.execute("""
        CREATE VIRTUAL TABLE fts_documents USING fts5(
            doc_type,
            doc_number,
            client_name,
            client_rut,
            section_content,
            content='',
            tokenize='unicode61'
        )
    """)

    # --- Trigger 4.0: auto-timestamp updated_at ---
    op.execute("""
        CREATE TRIGGER documents_updated_at
        AFTER UPDATE ON documents
        WHEN OLD.updated_at = NEW.updated_at
        BEGIN
            UPDATE documents
            SET updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
            WHERE id = NEW.id;
        END
    """)

    # --- Triggers 4.1: FTS sync on documents ---
    op.execute("""
        CREATE TRIGGER fts_documents_ai AFTER INSERT ON documents BEGIN
            INSERT INTO fts_documents(rowid, doc_type, doc_number, client_name, client_rut, section_content)
            SELECT NEW.id, NEW.type, NEW.number, c.name, c.rut, ''
            FROM clients c WHERE c.id = NEW.client_id;
        END
    """)
    op.execute("""
        CREATE TRIGGER fts_documents_au AFTER UPDATE ON documents BEGIN
            INSERT INTO fts_documents(fts_documents, rowid, doc_type, doc_number, client_name, client_rut, section_content)
            VALUES('delete', OLD.id, OLD.type, OLD.number, '', '', '');
            INSERT INTO fts_documents(rowid, doc_type, doc_number, client_name, client_rut, section_content)
            SELECT NEW.id, NEW.type, NEW.number, c.name, c.rut,
                CASE NEW.type
                    WHEN 'quote' THEN
                        COALESCE((SELECT observations FROM quotes WHERE document_id = NEW.id), '')
                    ELSE
                        COALESCE((
                            SELECT GROUP_CONCAT(rs.title || ' ' || COALESCE(rs.content, ''), ' ')
                            FROM report_sections rs WHERE rs.document_id = NEW.id
                        ), '')
                END
            FROM clients c WHERE c.id = NEW.client_id;
        END
    """)
    op.execute("""
        CREATE TRIGGER fts_documents_ad AFTER DELETE ON documents BEGIN
            INSERT INTO fts_documents(fts_documents, rowid, doc_type, doc_number, client_name, client_rut, section_content)
            VALUES('delete', OLD.id, OLD.type, OLD.number, '', '', '');
        END
    """)

    # --- Triggers 4.2: FTS sync on report_sections ---
    op.execute("""
        CREATE TRIGGER fts_sections_ai AFTER INSERT ON report_sections BEGIN
            INSERT INTO fts_documents(fts_documents, rowid, doc_type, doc_number, client_name, client_rut, section_content)
            VALUES('delete', NEW.document_id, '', '', '', '', '');
            INSERT INTO fts_documents(rowid, doc_type, doc_number, client_name, client_rut, section_content)
            SELECT d.id, d.type, d.number, c.name, c.rut,
                COALESCE((
                    SELECT GROUP_CONCAT(rs.title || ' ' || COALESCE(rs.content, ''), ' ')
                    FROM report_sections rs WHERE rs.document_id = d.id
                ), '')
            FROM documents d JOIN clients c ON d.client_id = c.id
            WHERE d.id = NEW.document_id;
        END
    """)
    op.execute("""
        CREATE TRIGGER fts_sections_au AFTER UPDATE ON report_sections BEGIN
            INSERT INTO fts_documents(fts_documents, rowid, doc_type, doc_number, client_name, client_rut, section_content)
            VALUES('delete', NEW.document_id, '', '', '', '', '');
            INSERT INTO fts_documents(rowid, doc_type, doc_number, client_name, client_rut, section_content)
            SELECT d.id, d.type, d.number, c.name, c.rut,
                COALESCE((
                    SELECT GROUP_CONCAT(rs.title || ' ' || COALESCE(rs.content, ''), ' ')
                    FROM report_sections rs WHERE rs.document_id = d.id
                ), '')
            FROM documents d JOIN clients c ON d.client_id = c.id
            WHERE d.id = NEW.document_id;
        END
    """)
    op.execute("""
        CREATE TRIGGER fts_sections_ad AFTER DELETE ON report_sections BEGIN
            INSERT INTO fts_documents(fts_documents, rowid, doc_type, doc_number, client_name, client_rut, section_content)
            VALUES('delete', OLD.document_id, '', '', '', '', '');
            INSERT INTO fts_documents(rowid, doc_type, doc_number, client_name, client_rut, section_content)
            SELECT d.id, d.type, d.number, c.name, c.rut,
                COALESCE((
                    SELECT GROUP_CONCAT(rs.title || ' ' || COALESCE(rs.content, ''), ' ')
                    FROM report_sections rs WHERE rs.document_id = d.id
                ), '')
            FROM documents d JOIN clients c ON d.client_id = c.id
            WHERE d.id = OLD.document_id;
        END
    """)

    # --- Triggers 4.3: FTS sync on quotes.observations ---
    op.execute("""
        CREATE TRIGGER fts_quotes_ai AFTER INSERT ON quotes BEGIN
            INSERT INTO fts_documents(fts_documents, rowid, doc_type, doc_number, client_name, client_rut, section_content)
            VALUES('delete', NEW.document_id, '', '', '', '', '');
            INSERT INTO fts_documents(rowid, doc_type, doc_number, client_name, client_rut, section_content)
            SELECT d.id, d.type, d.number, c.name, c.rut, COALESCE(NEW.observations, '')
            FROM documents d JOIN clients c ON d.client_id = c.id
            WHERE d.id = NEW.document_id;
        END
    """)
    op.execute("""
        CREATE TRIGGER fts_quotes_au AFTER UPDATE OF observations ON quotes BEGIN
            INSERT INTO fts_documents(fts_documents, rowid, doc_type, doc_number, client_name, client_rut, section_content)
            VALUES('delete', NEW.document_id, '', '', '', '', '');
            INSERT INTO fts_documents(rowid, doc_type, doc_number, client_name, client_rut, section_content)
            SELECT d.id, d.type, d.number, c.name, c.rut, COALESCE(NEW.observations, '')
            FROM documents d JOIN clients c ON d.client_id = c.id
            WHERE d.id = NEW.document_id;
        END
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_report_sections_parent', table_name='report_sections')
    op.drop_table('report_sections')
    op.drop_index('idx_quote_items_position', table_name='quote_items')
    op.drop_table('quote_items')
    op.drop_table('send_log')
    op.drop_table('reports')
    op.drop_table('quotes')
    op.drop_index('idx_document_versions_doc', table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index('idx_documents_client_status', table_name='documents')
    op.drop_table('documents')
    op.drop_table('settings')
    op.drop_table('section_templates')
    op.drop_table('company_profile')
    op.drop_table('clients')
    # ### end Alembic commands ###

    op.execute("DROP TRIGGER IF EXISTS fts_quotes_au")
    op.execute("DROP TRIGGER IF EXISTS fts_quotes_ai")
    op.execute("DROP TRIGGER IF EXISTS fts_sections_ad")
    op.execute("DROP TRIGGER IF EXISTS fts_sections_au")
    op.execute("DROP TRIGGER IF EXISTS fts_sections_ai")
    op.execute("DROP TRIGGER IF EXISTS fts_documents_ad")
    op.execute("DROP TRIGGER IF EXISTS fts_documents_au")
    op.execute("DROP TRIGGER IF EXISTS fts_documents_ai")
    op.execute("DROP TRIGGER IF EXISTS documents_updated_at")
    op.execute("DROP TABLE IF EXISTS fts_documents")
